//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient_V2.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/DodajDoSlownika", ReplyAction="http://tempuri.org/ICalculator/DodajDoSlownikaResponse")]
        bool DodajDoSlownika(string value, string translation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/DodajDoSlownika", ReplyAction="http://tempuri.org/ICalculator/DodajDoSlownikaResponse")]
        System.Threading.Tasks.Task<bool> DodajDoSlownikaAsync(string value, string translation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Wyszukaj", ReplyAction="http://tempuri.org/ICalculator/WyszukajResponse")]
        string Wyszukaj(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Wyszukaj", ReplyAction="http://tempuri.org/ICalculator/WyszukajResponse")]
        System.Threading.Tasks.Task<string> WyszukajAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Usun", ReplyAction="http://tempuri.org/ICalculator/UsunResponse")]
        bool Usun(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Usun", ReplyAction="http://tempuri.org/ICalculator/UsunResponse")]
        System.Threading.Tasks.Task<bool> UsunAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Modyfikuj", ReplyAction="http://tempuri.org/ICalculator/ModyfikujResponse")]
        bool Modyfikuj(string value, string translation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Modyfikuj", ReplyAction="http://tempuri.org/ICalculator/ModyfikujResponse")]
        System.Threading.Tasks.Task<bool> ModyfikujAsync(string value, string translation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Wyswietl", ReplyAction="http://tempuri.org/ICalculator/WyswietlResponse")]
        System.Collections.Generic.Dictionary<string, string> Wyswietl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Wyswietl", ReplyAction="http://tempuri.org/ICalculator/WyswietlResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> WyswietlAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : WcfServiceClient_V2.ServiceReference2.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<WcfServiceClient_V2.ServiceReference2.ICalculator>, WcfServiceClient_V2.ServiceReference2.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DodajDoSlownika(string value, string translation) {
            return base.Channel.DodajDoSlownika(value, translation);
        }
        
        public System.Threading.Tasks.Task<bool> DodajDoSlownikaAsync(string value, string translation) {
            return base.Channel.DodajDoSlownikaAsync(value, translation);
        }
        
        public string Wyszukaj(string value) {
            return base.Channel.Wyszukaj(value);
        }
        
        public System.Threading.Tasks.Task<string> WyszukajAsync(string value) {
            return base.Channel.WyszukajAsync(value);
        }
        
        public bool Usun(string value) {
            return base.Channel.Usun(value);
        }
        
        public System.Threading.Tasks.Task<bool> UsunAsync(string value) {
            return base.Channel.UsunAsync(value);
        }
        
        public bool Modyfikuj(string value, string translation) {
            return base.Channel.Modyfikuj(value, translation);
        }
        
        public System.Threading.Tasks.Task<bool> ModyfikujAsync(string value, string translation) {
            return base.Channel.ModyfikujAsync(value, translation);
        }
        
        public System.Collections.Generic.Dictionary<string, string> Wyswietl() {
            return base.Channel.Wyswietl();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> WyswietlAsync() {
            return base.Channel.WyswietlAsync();
        }
    }
}
